// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsAlZEv3wJ2Toa1Z27vBoPsJT2k1Pq9uA',
    appId: '1:1073116230665:web:faed3b49d870305988b4d8',
    messagingSenderId: '1073116230665',
    projectId: 'todo-73efa',
    authDomain: 'todo-73efa.firebaseapp.com',
    storageBucket: 'todo-73efa.appspot.com',
    measurementId: 'G-XWN1ZE9FLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLbTDpNlCE4PEISWWQzs7Y1TW3iJEBWWg',
    appId: '1:1073116230665:android:85b041754bd60cc988b4d8',
    messagingSenderId: '1073116230665',
    projectId: 'todo-73efa',
    storageBucket: 'todo-73efa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRAjqkU4DptX6_hCA27iuoI3_70T5mhWg',
    appId: '1:1073116230665:ios:b68a6f4cbab63d4188b4d8',
    messagingSenderId: '1073116230665',
    projectId: 'todo-73efa',
    storageBucket: 'todo-73efa.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRAjqkU4DptX6_hCA27iuoI3_70T5mhWg',
    appId: '1:1073116230665:ios:63bebcc8c3585f7488b4d8',
    messagingSenderId: '1073116230665',
    projectId: 'todo-73efa',
    storageBucket: 'todo-73efa.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
